### ISSUE TITLE
您好，请问这个数据集可以提供法条推荐的标签和刑期长短的标签吗？

### ISSUE THREAD

**Issue by hecongqing** [thunlp/attribute_charge#11]

**Comment by hecongqing** [comment]
我在看论文时，你用该数据集评估了Fact-Law Attention Model(Luo et al. 2017)这篇文章，而这篇文章需要借助法条推荐任务，请问您能否提供这三个数据集的法条推荐标签和刑期长短标签呢？非常感谢！

**Comment by zig-kwin-hu** [comment]
你好，我们只是复现了Fact-Law Attention Model的模型，没有在他们的数据集上跑过实验，所以抱歉不能提供。

**Comment by zig-kwin-hu** [comment]
无法提供此数据集。

**Comment by zig-kwin-hu** [comment]
无法提供此数据集。

**Comment by zig-kwin-hu** [comment]
。
