### ISSUE TITLE
about dataset information

### ISSUE THREAD

**Issue by ddgetget** [thunlp/attribute_charge#12]
how to understander the dataset struct

**Comment by ddgetget** [comment]
for example :
0	14	放火罪	2047	1	1	2	1	1	0	1	2	0	2
what's the mean of those numbner?

**Comment by xcjthu** [comment]
The last ten numers refer to the lables of ten attributes. Specifically, 0 refers to yes (contains the attribute), 1 refers to no (do not contains the attribute), and 2 refers to unrelated (unrelated to the attribute)
