### ISSUE TITLE
关于代码的一些疑惑与结果复现

### ISSUE THREAD

**Issue by AlexYangLi** [thunlp/attribute_charge#3]
- 代码疑惑1
**model.py**中，125行的**unmasked_attr_loss**的shape是[batch_size,]，126行的**attr_mask**的shape是[batch_size, 1]，两者经过**tf.multiply**后的**attr_loss**的shape就会是[batch_size, batch_size]。是不是应该先把**attr_mask** reshape成[batch_size,]？

- 代码疑惑2
**model.py**中，71行是否应该用**tf.reduce_mean**而非**tf.reduce_sum**？

- 结果复现
这是我复现的结果：**Acc: 93.4; MP: 56.9; MR: 57.7; F1: 55.6**。F1值没有达到论文的**64.9**，想知道这可能是什么原因造成的？谢谢！

**Comment by zig-kwin-hu** [comment]
我们为了提高代码可读性，重构了我们的代码，并由此带来了这些问题。感谢您的意见，我们最近会提交正确的代码。

**Comment by zig-kwin-hu** [comment]
您好，我们的上传了修正后的代码，由于一定的随机性，可能F1值会在62到64.9之间。

**Comment by tucunchao** [comment]
我们已经修复了之前代码中的bug，目前的版本能够达到论文中汇报的结果
