### ISSUE TITLE
May you apply Criminal-M  and Criminal-L dataset?

### ISSUE THREAD

**Issue by hecongqing** [thunlp/attribute_charge#5]
Hello , This is very Contributing work for us! I am very interested in this work , May you apply Criminal-M  and Criminal-L dataset?

**Comment by zig-kwin-hu** [comment]
Sure, we will upload Criminal-M and Criminal-L soon.

**Comment by hecongqing** [comment]
> Sure, we will upload Criminal-M and Criminal-L soon.
thank you very much

**Comment by hecongqing** [comment]
> Sure, we will upload Criminal-M and Criminal-L soon.

Sorry, I’m bothered again.I didn't find your latest data set about Criminal-M and Criminal-L.

**Comment by zig-kwin-hu** [comment]
We have update our readme and you can find the link.
