### ISSUE TITLE
读取“words.vec”文件时，遇到如下图的一个问题，一直未能解决

### ISSUE THREAD

**Issue by caoyunfei1024** [thunlp/attribute_charge#8]
![Uploading Screenshot from 2018-12-18 22-17-10.png…]()

**Comment by caoyunfei1024** [comment]
![screenshot from 2018-12-18 22-17-10](https://user-images.githubusercontent.com/44258557/50266078-232afc00-045d-11e9-8176-2c76953db98a.png)

**Comment by caoyunfei1024** [comment]
我之前给您发过邮件,说在这里会有同学回复,估计也是"炜"的问题

**Comment by caoyunfei1024** [comment]
该怎么解决呢?

**Comment by zibuyu** [comment]
已经安排同学确认你提出的问题原因。建议 @caoyunfei1024 善用github issue系统进行提问和交流，同一个问题连发四个信息，没有必要。

**Comment by zig-kwin-hu** [comment]
你好，我在python 2.7.12环境下没有出现你这个问题。在Python 3.6.5 下出现了这个问题，应当是python3和python2编码的差别导致的。可以搭建一个python2的虚拟环境来解决。如果还想用python3的话，也可以参考[这个链接](https://stackoverflow.com/questions/19699367/unicodedecodeerror-utf-8-codec-cant-decode-byte)。

**Comment by caoyunfei1024** [comment]
> 你好，我在python 2.7.12环境下没有出现你这个问题。在Python 3.6.5 下出现了这个问题，应当是python3和python2编码的差别导致的。可以搭建一个python2的虚拟环境来解决。如果还想用python3的话，也可以参考[这个链接](https://stackoverflow.com/questions/19699367/unicodedecodeerror-utf-8-codec-cant-decode-byte)。

不是很明白为什么会出现could not convert string to float: '炜'
